### ISSUE TITLE
Date's timezones

### ISSUE THREAD

**Issue by obrunsmann** [GetStream/stream-feed-flutter#144]
Hello,

we're migrating to this package from our own Stream API implementation. While all the timestamps coming from the API are UTC we also need to parse them as UTC to let them automatically convert into local time.

What I've done was:
```dart
DateTime.parse('${json['time'] as String}Z')
```

This worked perfectly fine and got converted in the local timezone.

Right now:
```dart
print(activity.time!.isUtc);
```

Prints _false_ which is not correct - the time actually is UTC :/

**Comment by obrunsmann** [comment]
Yeah nice! So do you need something from me? I am here to test any time

**Comment by sachaarbonel** [comment]
@obrunsmann I'll push a fix this week and ping you when it's done so you can try out

**Comment by sachaarbonel** [comment]
hey, @obrunsmann I addressed your issues in #167 along with the recent issues you opened (#165,#163), can you let me know if this works for you? Keep in mind that it is based on our recent release (0.4.0) that includes some breaking changes like supporting generics. Here is the [release note](https://github.com/GetStream/stream-feed-flutter/releases/tag/v0.4.0) in case you need it.
 
You can try it out like this:
```yaml
dependencies:   
  stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: support-extraData-null-value
       path: ./packages/stream_feed

```
