### ISSUE TITLE
Getting Following Feeds

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#70]
When I try to get the feeds that the current user is following I get null trying to access the data. If you look at the response from the request it shows there is indeed data but using `value[0].target ` or `value[0]` each returns null.
```
I/flutter (17428): *** Request ***
I/flutter (17428): uri: https://api.stream-io-api.com/api/v1.0/feed/timeline/Prhia3HUNgPesoCjkaEdEUPuOWZ2personal/following?limit=100&offset=0&api_key=hmwext26344q&location=unspecified
I/flutter (17428): method: GET
I/flutter (17428): responseType: ResponseType.json
I/flutter (17428): followRedirects: true
I/flutter (17428): connectTimeout: 10000
I/flutter (17428): sendTimeout: 0
I/flutter (17428): receiveTimeout: 10000
I/flutter (17428): receiveDataWhenStatusError: true
I/flutter (17428): extra: {}
I/flutter (17428): headers:
I/flutter (17428):  stream-auth-type: jwt
I/flutter (17428):  x-stream-client: stream-feed-dart-client-android-0.1.3
I/flutter (17428):  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiUHJoaWEzSFVOZ1Blc29DamthRWRFVVB1T1daMnBlcnNvbmFsIn0.L8Yu4YxwCb4JykadVwlwTJyidBhIerqGpWn1LAK0Sj4
I/flutter (17428): data:
I/flutter (17428): null
I/flutter (17428):
I/flutter (17428): *** Response ***
I/flutter (17428): uri: https://api.stream-io-api.com/api/v1.0/feed/timeline/Prhia3HUNgPesoCjkaEdEUPuOWZ2personal/following?limit=100&offset=0&api_key=hmwext26344q&location=unspecified
I/flutter (17428): statusCode: 200
I/flutter (17428): headers:
I/flutter (17428):  connection: keep-alive
I/flutter (17428):  cache-control: no-cache
I/flutter (17428):  x-ratelimit-reset: 1621443000
I/flutter (17428):  date: Wed, 19 May 2021 16:49:38 GMT
I/flutter (17428):  access-control-allow-origin: *
I/flutter (17428):  x-ratelimit-limit: 500
I/flutter (17428):  content-encoding: gzip
I/flutter (17428):  x-ratelimit-remaining: 499
I/flutter (17428):  content-type: application/json;charset=utf-8
I/flutter (17428):  access-control-max-age: 86400
I/flutter (17428):  server: nginx
I/flutter (17428):  access-control-allow-headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type
I/flutter (17428):  access-control-allow-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
I/flutter (17428):  content-length: 192
I/flutter (17428): Response Text:
I/flutter (17428): {"results":[{"feed_id":"timeline:Prhia3HUNgPesoCjkaEdEUPuOWZ2personal","target_id":"user:WPpmnSSN1uURXNODPak2rlsCV332personal","created_at":"2021-05-14T19:58:27.274792063Z","updated_at":"2021-05-14T19:58:27.274792063Z"}],"duration":"1.62ms"}
I/flutter (17428):
I/flutter (17428): Following: Follow(null, null)
```

**Comment by sachaarbonel** [comment]
Looking at the history it looks like the model got changed. Working on a fix

**Comment by xsahil03x** [comment]
@sachaarbonel in `Follow.dart` add `jsonKey` and regenerate models

```dart
/// The combination of feed slug and user id separated by a colon  
///For example: flat:1  
@JsonKey(name: 'feed_id')
final String? source;

/// the id of the feed you want to follow 
@JsonKey(name: 'target_id')
final String? target;
```

**Comment by rlee1990** [comment]
@sachaarbonel  @xsahil03x thanks will give this a go

**Comment by sachaarbonel** [comment]
hey @rlee1990 the fix landed! can you check it worked:
```yaml
dependencies:   
  stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: fix-issue-70
       path: ./packages/stream_feed
```

**Comment by rlee1990** [comment]
Will do right now thanks

**Comment by rlee1990** [comment]
@sachaarbonel It is still not working. I still get the same issue.

**Comment by sachaarbonel** [comment]
did you use the fix branch? https://github.com/GetStream/stream-feed-flutter/issues/70#issuecomment-845127315

**Comment by rlee1990** [comment]
Yes
stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: fix-issue-70
       path: ./packages/stream_feed

**Comment by rlee1990** [comment]
My pubspec.lock file output:
```
 stream_feed:
    dependency: "direct main"
    description:
      path: "./packages/stream_feed"
      ref: fix-issue-70
      resolved-ref: "5616ac406830b609d31e4c97357a70dea9198352"
      url: "https://github.com/GetStream/stream-feed-flutter.git"
    source: git
    version: "0.1.3"
```
