### ISSUE TITLE
Subscribing to the feed only gives activities of Type activity and not Enriched Activity

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#91]
Subscribing to the feed only gives activities of Type activity and not Enriched Activity.

Using version: 
```
stream_feed:
    dependency: "direct main"
    description:
      path: "./packages/stream_feed"
      ref: fix-issue-89
      resolved-ref: "67d28575b6d41cbbbc155f02a00e25319b5faefa"
      url: "https://github.com/GetStream/stream-feed-flutter.git"
    source: git
    version: "0.2.1"
```

**Comment by sachaarbonel** [comment]
Hey @rlee1990 I think there are two many parameters in your YAML file and the "version" is taking over the git dependency. Just keep URL, ref, and path.

**Comment by rlee1990** [comment]
@sachaarbonel thats from the pubspec.lock file
This is my yaml file:
```
stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: fix-issue-89
       path: ./packages/stream_feed
```
